project02_ver2: project02_ver2_main.o project02_ver2.o
	gcc -o project02_ver2 project02_ver2_main.c project02_ver2.c

project02_ver2_main.o: project02_ver2_main.c
	gcc -c project02_ver2.h project02_ver2_main.c

project02_ver2.o: project02_ver2.c
	gcc -c project02_ver2.h project02_ver2.c
